---
title: "Lab 02 - Data Viz"
author: "Your Name Goes Here"
date: "01/01/2022"
output: pdf_document
editor_options: 
  chunk_output_type: console
---



```{r load-packages, message = FALSE, echo = FALSE, warning=FALSE}
#Load Packages and Data Preprocessing
library(tidyverse)
library(scales)
library(viridis)
```


```{r datawrangle, echo=FALSE, message=FALSE, warning=FALSE}


library(readxl)

fert=read_excel("worldbank_fertility_1960.2020.xls",sheet=1)

#now pivot to facilitate combination

fertlong <- 
  fert %>%
  select(-c("Indicator Name","Indicator Code")) %>%
  pivot_longer(cols = "1960":"2020", names_to = "Year", values_to = "Fertility Rate")

pop=read_excel("worldbank_population_1960.2021.xls",sheet=1)

poplong <- 
  pop %>%
  select(-c("Indicator Name","Indicator Code")) %>%
  pivot_longer(cols = "1960":"2021", names_to = "Year", values_to = "Population")

#combine the two data sources 
worldbank <- right_join(fertlong,poplong)
worldbank$Year=as.numeric(worldbank$Year)

#restricting to countries, excluding some regions, reporting areas of interest, and semi-autonomous regions

worldbankcountries <- worldbank %>% filter(`Country Name` %in% c("Aruba","Afghanistan","Angola","Albania","Andorra","United Arab Emirates","Argentina","Armenia","American Samoa","Antigua and Barbuda","Australia","Austria","Azerbaijan","Burundi","Belgium","Benin","Burkina Faso","Bangladesh","Bulgaria","Bahrain","The Bahamas","Bosnia and Herzegovina", "Belarus","Belize","Bermuda","Bolivia","Brazil","Barbados","Brunei Darussalam","Bhutan","Botswana","Central African Republic","Canada","Switzerland","Channel Islands","Chile","China","Cote d'Ivoire","Cameroon","Congo, Dem. Rep.","Congo, Rep.","Colombia","Comoros","Cabo Verde","Costa Rica","Cuba","Curacao","Cayman Islands","Cyprus","Czech Republic","Germany","Djibouti","Dominica","Denmark","Dominican Republic","Algeria","Ecuador","Egypt, Arab Rep.","Eritrea","Spain","Estonia","Ethiopia","Finland","Fiji","France","Faroe Islands","Micronesia, Fed. Sts.","Gabon","United Kingdom","Georgia","Ghana","Gibraltar","Guinea","The Gambia","Guinea-Bissau","Equatorial Guinea","Greece","Grenada","Greenland","Guatemala","Guam","Guyana","Honduras","Croatia","Haiti","Hungary","Indonesia","Isle of Man","India","Ireland","Iran, Islamic Rep.","Iraq","Iceland","Israel","Italy","Jamaica","Jordan","Japan","Kazakhstan","Kenya","Kyrgyz Republic","Cambodia","Kiribati","St. Kitts and Nevis","Korea, Rep.","Kuwait","Lao PDR","Lebanon","Liberia","Libya","St. Lucia","Liechtenstein","Sri Lanka","Lesotho","Lithuania","Luxembourg","Latvia","St. Martin","Morocco","Monaco","Moldova","Madagascar","Maldives","Mexico","Marshall Islands","North Macedonia","Mali","Malta","Myanmar","Montenegro","Mongolia","Northern Mariana Islands","Mozambique","Mauritania","Mauritius","Malawi","Malaysia","Namibia","New Caledonia","Niger","Nigeria","Nicaragua","Netherlands","Norway","Nepal","Nauru","New Zealand","Oman","Pakistan","Panama","Peru","Philippines","Palau","Papua New Guinea","Poland","Korea, Dem. People's Rep.","Portugal","Paraguay","French Polynesia","Qatar","Romania","Russian Federation","Rwanda","Saudi Arabia","Sudan","Senegal","Singapore","Solomon Islands","Sierra Leone","El Salvador","San Marino","Somalia","Serbia","South Sudan","Sao Tome and Principe","Suriname","Slovak Republic","Slovenia","Sweden","Eswatini","Sint Maarten","Seychelles","Syrian Arab Republic","Turks and Caicos Islands","Chad","Togo","Thailand","Tajikistan","Turkmenistan","Timor-Leste","Tonga","Trinidad and Tobago","Tunisia","Turkiye","Tuvalu","Tanzania","Uganda","Ukraine","Uruguay","United States","Uzbekistan","St. Vincent and the Grenadines","Venezuela, RB","British Virgin Islands","Virgin Islands (U.S.)","Vietnam","Vanuatu","Samoa","Kosovo","Yemen, Rep.","South Africa","Zambia","Zimbabwe")) 
```

# Exercise 1

(Your response here.)


```{r ex1, echo=FALSE}

```


# Exercise 2

(Your response here.)



```{r ex2, message=FALSE}
worldbankcountries$logpop = log(worldbankcountries$Population)

```


# Exercise 3

(Your response here.)


```{r ex3}


```

# Exercise 4

(Your response here.)

```{r ex4, message=FALSE, warning=FALSE}


```


# Exercise 5

(Your response here.)

```{r ex5, warning=FALSE, message=FALSE}


```

# Exercise 6

(Your response here.)


```{r ex6, warning=FALSE, message=FALSE}



```



